Repository Group-3-Website-Project/Group-3-Website-Project, pull requests merged in 2025-03, with the labels that each got.

#1 Merge Project Setup to Staging
  .github/pull_request_template.md
  .gitignore
  README.md
  assets/Off-Topic.jpg
  index.html
  package-lock.json
  package.json
  src/input.css
  src/sections/contact.html
  src/sections/footer.html
  src/sections/header.html
  src/sections/hero.html
  tailwind.config.js
Labels: Done

#6 Fix: fix tailwind dependencies vulnerability issue
  package-lock.json
Labels: Done

#2 UPD: Implement the nav bar
  .DS_Store
  assets/.DS_Store
  assets/img/.DS_Store
  assets/img/Baumeister.svg
  assets/img/cancel.svg
  assets/img/menu.svg
  index.html
  src/sections/header.html
  tailwind.config.js
Labels: Done

#8 Update: build acehotel Section
  .DS_Store
  assets/.DS_Store
  assets/img/.DS_Store
  assets/img/acehotel.svg
  assets/img/yellow.svg
  index.html
  src/sections/about.html
  src/sections/acehotel.html
  tailwind.config.js
Labels: WIP

#16 Fix: unelevated nav and nav items
  src/sections/header.html
Labels: Done

#9 Made the brand strategy section
  index.html
  src/sections/brand-strategy.html
Labels: Done

#10 Ft/footer
  .DS_Store
  assets/.DS_Store
  assets/red.svg
  src/sections/footer.html
Labels: Done

#23 Fix: scrollable nav dropdown (issue#21)
  index.html
Labels: Done

#19 Fix: sticky navbar (issue#15)
  index.html
  src/sections/header.html
  tailwind.config.js
Labels: Done

#27 fix: made the yellow shape sticky
  index.html
  src/sections/about.html
  tailwind.config.js
Labels: Done

#25 Fix: Remove the contact section from the landing page
  index.html
Labels: Done

#24 Fix: fix the desktop version of the navbar
  src/sections/header.html
Labels: Done

#28 Fix: Changed logo from image to text
  assets/img/Baumeister.svg
  assets/img/gray.svg
  contact.html
  src/sections/header.html
Labels: Done

#33 fix(css): logo background behavior
  src/sections/about.html
  src/sections/header.html
Labels: Done

#34 fix: renamed the wrappers of the sections and deleted the contact.htm…
  imprint.html
  index.html
  src/sections/acehotel.html
  src/sections/brand-strategy.html
  src/sections/contact.html
  src/sections/footer.html
  src/sections/header.html
  src/sections/hero.html
  src/sections/legal-notice.html
Labels: Done

#22 Fix: missing the dropdown background shapes (issue#14)
  assets/img/shapes.svg
  src/sections/header.html
Labels: Done

#36 Ft/data privacy
  privacy-policy.html
  src/sections/data_privacy.html
Labels: Done

#37 fix: fixing the padding along the x-axis of the acehotel on all break…
  src/sections/acehotel.html
Labels: bug, Done

#43 Chore: fix privacy policy page and imprint page titles
  imprint.html
  privacy-policy.html
Labels: Done

#41 39 li wrapping a not the other way
  src/sections/header.html
Labels: Done

#44 Feat: Add imprint and privacy policy links to footer
  src/sections/footer.html
Labels: Done

#51 Chore: fix a wrapping a div semantic
  src/sections/header.html
Labels: Done

#47 fix(ui): nav dropdown not showing on non-index pages
  imprint.html
  privacy-policy.html
  src/sections/header.html
Labels: Done

#52 Fix: non fixed nav dropdown
  src/sections/header.html
Labels: Done

#50 Chore: remove more arbitrary values (check if it all still work!!!!!)
  src/sections/about.html
  src/sections/brand-strategy.html
  src/sections/footer.html
  src/sections/hero.html
Labels: Done

#55 Bg/54 navbar isnt sticky for non index pages
  imprint.html
  privacy-policy.html
  src/sections/header.html
Labels: Done
